project:
  type: book

book:
  author: "Norah Jones"
  date: "8/13/2022"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

profile:
  default: pro
  group: [pro, base]
  config:
    pro: config/pro.yml
    base: config/base.yml
  
quarto-required: 1.2.89

