project:
  type: book

book:
  title: "multi-version-book"
  author: "Norah Jones"
  date: "8/13/2022"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

metadata-files: 
  - config/config.yml

