project:
  type: book

book:
  author: "Norah Jones"
  date: "8/13/2022"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

profile:
  default: base
  group: [pro, base]
  
quarto-required: 1.2.92

